---
nodeFlags:
  bootnode: false
  privacy: false

azure:
  # the script/bootstrap.sh uses the name 'default-pod-identity' so only change this if you altered the name
  identityName: default-pod-identity
  # the clientId of the user assigned managed identity created in the template
  identityClientId: goq-prod-ops-identity
  keyvaultName: goq-prod-vault
  # the tenant ID of the key vault
  tenantId: [TODO]
